### ISSUE TITLE
Gatus: Allow the way to pass sensitive keys as header

### ISSUE THREAD

**Issue by shvkumara** [minicloudlabs/helm-charts#102]
We have endpoint healthcheck, and to query/hit that endpoint. we need to pass API-KEY as part of the header,

My current override of config for helm.
```
config:
  endpoints:
    - name: sample-api
      group: production
      url: https://my-api-prod.av.cloud.pan.local/healthcheck
      headers:
        API-KEY: my-api-key-value
      interval: 60s
      client:
        insecure: true
      conditions:
        - "[STATUS] == 200"
        - "[CERTIFICATE_EXPIRATION] > 72h"
```

   Currently, I am putting them as part of the config section in override, And I cannot push this to any of repos or artifactor. 

Can I make this available through a k8s secret?
