### ISSUE TITLE
Unable to install with Helm 

### ISSUE THREAD

**Issue by Sumtin** [minicloudlabs/helm-charts#63]
I've been unable to get Gatus running on my minik8s cluster, even using the [example Helm chart](https://github.com/minicloudlabs/helm-charts/tree/main/charts/gatus#helmfileyaml-example).

Not matter which config I use, I get this error:
```
2023/03/11 02:44:48 [config][LoadConfiguration] Reading configuration from configFile=
panic: configuration should contain at least 1 endpoint

goroutine 1 [running]:
main.main()
      /app/main.go:19 +0x168 
Stream closed EOF for default/gatus-1678502686-56b989d6fb-lh8lh (gatus) 
```
My actual config:
```
---
repositories:
  - name: minicloudlabs
    url: https://minicloudlabs.github.io/helm-charts

releases:
  - name: gatus
    namespace: gatus
    chart: minicloudlabs/gatus
    version: 3.1.5
    values:
      - podLabels: pod-gatus
      - service:
        port: 30010
      - persistence:
          enabled: true
          existingClaim: 2g-pvc-nfs-nas
      - config:
          storage:
            type: sqlite
            path: /data/data.db
          alerting:
            discord:
              webhook-url: "https://discord.com/api/webhooks/***/***"
          endpoints:
            - name: IMPORTANT-remember-privacy-policy
              group: core
              url: "https://www.remember-game.com/privacy/"
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
                - type: discord
                  enabled: true
                  send-on-resolved: true
                  description: "*** REMEMBER Privacy Policy DOWN ***"
```

The claim exists:
![image](https://user-images.githubusercontent.com/6676557/224462555-6a586304-1c46-4c61-a533-4e1c33600a95.png)

Any help would be appreciated.

**Comment by avakarev** [comment]
Hi @Sumtin, your config looks almost perfect. `podLabels` should be a map instread of string, maybe helm parses deployment template incorrectly because of that. Can you try to comment out `- podLabels: pod-gatus` and re-run your deployment?

**Comment by Sumtin** [comment]
Didn't fix. I trimmed my config down to the basics to try and remove variables in my local config, but failing with same error.  New config:

```
---
repositories:
  - name: minicloudlabs
    url: https://minicloudlabs.github.io/helm-charts

releases:
  - name: gatus
    namespace: gatus
    chart: minicloudlabs/gatus
    version: 3.1.5
    values:
      - service:
          port: 30011
      - persistence:
          enabled: false
      - config:
          endpoints:
            - name: IMPORTANT-remember-privacy-policy
              group: core
              url: "https://www.remember-game.com/privacy/"
              interval: 1m
              conditions:
                - "[STATUS] == 200"
```

**Comment by avakarev** [comment]
@Sumtin Unfortunately I can't reproduce the issue using your helmfile.

The error message from gatus tells about missing config.

Could you please show your config map `kubectl get configmap gatus -n gatus -o yaml`?

**Comment by Sumtin** [comment]
My maps:
![image](https://user-images.githubusercontent.com/6676557/225072927-3731be38-3e47-489f-891e-837d414b0917.png)

The config map showing empty `config.yaml`:
![image](https://user-images.githubusercontent.com/6676557/225073077-84d5900b-4009-404a-b777-b3f1532b4591.png)

I'm new to k8s, so it's probably something on my end.  I'm running microk8s.

**Comment by avakarev** [comment]
Right, it's empty and this is the problem. I guess the config values aren't set on deployment. How do you deploy? Are you using https://github.com/roboll/helmfile or anything else?

**Comment by avakarev** [comment]
I also noticed your namespace is `default`, so I guess you deployed chart not correctly. This is what you need to do.
1. Undeploy the chart from `default` ns: `helm uninstall gatus -n default`
2. Create `helmfile.yaml`, fill it with content of your `actual config` from your first message.
3. Ensure your have installed [helm](https://github.com/helm/helm) and [helmfile](https://github.com/roboll/helmfile)
4. Run `helmfile -f helmfile.yaml sync`
5. Check if the gatus is healthy and has the endpoints as you expect.

**Comment by avakarev** [comment]
@Sumtin is the issue solved now? Are you good to close this ticket?

**Comment by avakarev** [comment]
@Sumtin you are almost good. Your config has invalid yaml, so it's parsed not as expected. Please indent `port: 30010` with two more spaces and your helmfile should finally do the job. So, this is the final version of your hemlfile:
```yaml
---
repositories:
  - name: minicloudlabs
    url: https://minicloudlabs.github.io/helm-charts

releases:
  - name: gatus
    namespace: gatus
    chart: minicloudlabs/gatus
    version: 3.1.5
    values:
      - service:
          port: 30010
      - persistence:
          enabled: true
          existingClaim: 2g-pvc-nfs-nas
      - config:
          storage:
            type: sqlite
            path: /data/data.db
          alerting:
            discord:
              webhook-url: "https://discord.com/api/webhooks/***/***"
          endpoints:
            - name: IMPORTANT-remember-privacy-policy
              group: core
              url: "https://www.remember-game.com/privacy/"
              interval: 1m
              conditions:
                - "[STATUS] == 200"
              alerts:
                - type: discord
                  enabled: true
                  send-on-resolved: true
                  description: "*** REMEMBER Privacy Policy DOWN ***"
```
