### ISSUE TITLE
Service resources in helm template not working

### ISSUE THREAD

**Issue by yuvals41** [minicloudlabs/helm-charts#91]
Hello,

I have made my own values file to your helm, I see that I cant reach gatus because the helm chart does not render the service resource correctly

I have set this value(which is the default) on my values.yaml file:
````
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}
  labels: {}
````

and when i do ```helm template -f values.yaml gatus minicloudlabs/gatus``` i get these fields:

```
# Source: gatus/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: mynamespace
  labels:
    helm.sh/chart: gatus-3.4.0
    app.kubernetes.io/name: gatus
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/version: "v5.5.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: gatus
    app.kubernetes.io/instance: gatus
```
 which is forwarding the traffic to the container on HTTP(port 80) which is incorrect, its supposed to be 8080
 I even tried with your default value file and got the same result
 
 I would be happy this issue would be fixed so i can access the gatus service
 
 Thank you
